Repository MicrosoftDocs/azure-devops-docs, pull requests merged in 2019-12, with the labels that each got.

#4376 Update with minimatch pattern for excluding files by extension
  docs/pipelines/tasks/utility/delete-files.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#6501 Fix incorrectly encoded mdash
  docs/boards/get-started/what-is-azure-boards.md
Labels: Change sent to author, devops-new-user/tech, devops/prod, do-not-merge

#6498 Add information about key value par format in bake action
  docs/pipelines/tasks/deploy/kubernetes-manifest.md
Labels: Change sent to author, assessing_(C&L), devops-cicd/tech, devops/prod, do-not-merge

#6529 Correction to link URL in set-area-paths.md
  docs/organizations/settings/set-area-paths.md
Labels: Change sent to author, devops-agile/tech, devops/prod, do-not-merge

#6530 Update permissions-access.md
  docs/organizations/security/permissions-access.md
Labels: Change sent to author, devops-security/tech, devops/prod, do-not-merge

#6538 Fix missing headers not displayed correctly
  docs/repos/git/forks.md
Labels: Change sent to author, devops-code-git/tech, devops/prod, do-not-merge

#6054 Remove "configuration" key from "inputs" list (#6053)
  docs/pipelines/tasks/_shared/yaml/DotNetCoreCLIV2.md
Labels: assessing_(C&L), do-not-merge, review-team-triage

#4409 Updated Publish Code Coverage Results task documentation
  docs/pipelines/tasks/test/publish-code-coverage-results.md
Labels: Change sent to author, assessing_(C&L), devops-cicd/tech, devops/prod, do-not-merge

#6539 Update Section on ConnectALL
  docs/reference/tfs-ps-sync/sync-ps-tfs.md
Labels: Change sent to author, assessing_(C&L), devops-agile/tech, devops/prod, do-not-merge

#6547 Update DownloadPipelineArtifactV2.md
  docs/pipelines/tasks/_shared/yaml/DownloadPipelineArtifactV2.md
Labels: assessing_(C&L), do-not-merge, review-team-triage

#6546 Update install-extensions.md
  docs/marketplace/install-extension.md
Labels: Change sent to author, assessing_(C&L), devops-marketplace/tech, devops/prod, do-not-merge

#6572 Fix link warnings and moniker in public PR
  docs/marketplace/install-extension.md
  docs/marketplace/request-extensions.md
Labels: Change sent to author, devops-marketplace/tech, devops/prod, do-not-merge

#6571 wrong parameter names
  docs/marketplace/install-extension.md
Labels: Change sent to author, devops-marketplace/tech, devops/prod, ready-to-merge

#6586 Fixed inconsistency in markdown-guidance.md
  docs/project/wiki/markdown-guidance.md
Labels: Change sent to author, devops-collab/tech, devops/prod, ready-to-merge

#6587 Added missing verb to markdown-guidance.md
  docs/project/wiki/markdown-guidance.md
Labels: Change sent to author, devops-collab/tech, devops/prod, ready-to-merge

#6602 Updated GitHub repo links to use the new URLs
  docs/integrate/get-started/client-libraries/samples.md
Labels: Change sent to author, devops-ecosystem/tech, devops/prod, ready-to-merge

#6596 Cleanup: Removed an unnecessary character
  docs/boards/work-items/best-tool-add-update-link-work-items.md
Labels: Change sent to author, devops-agile/tech, devops/prod, do-not-merge

#6605 Added missing ".com" in URL dev.azure.com
  docs/repos/git/get-started-vs2013.md
Labels: Change sent to author, devops-code-git/tech, devops/prod, do-not-merge

#6621 Add a single space in Markdown file
  docs/extend/develop/add-backlog-panel.md
Labels: Change sent to author, devops-ecosystem/tech, devops/prod, do-not-merge

#6623 Removing the release note for Cross organization wiki search
  release-notes/2019/_shared/wiki/sprint-159-update.md
Labels: Change sent to author, assessing_(C&L), devops-release-notes/tech, devops/prod, do-not-merge

#6631 updated soft-delete period to 28
  docs/organizations/security/data-protection.md
Labels: do-not-merge

#6642 Removing link to fix validation warnings in private repo
  release-notes/2019/_shared/wiki/sprint-159-update-links.md
Labels: Change sent to author, devops-release-notes/tech, devops/prod, do-not-merge

#6653 Fixing broken links (installed software on microsoft-hosted agents)
  docs/pipelines/agents/hosted.md
Labels: Change sent to author, assessing_(C&L), devops-cicd/tech, devops/prod, ready-to-merge

#6665 Fixed title and link to Azure DevOps Blog
  docs/user-guide/alm-devops-features.md
Labels: Change sent to author, devops-new-user/tech, devops/prod, ready-to-merge

#6607 Fix: Casing should be consistent
  docs/report/powerbi/sample-odata-overview.md
Labels: Change sent to author, assessing_(C&L), devops-analytics/tech, devops/prod, do-not-merge

#6604 Renamed "OrganizationName" --> "CollectionName" for on-prem
  docs/report/extend-analytics/odata-api-version.md
Labels: Change sent to author, assessing_(C&L), devops-analytics/tech, devops/prod, do-not-merge

#6603 Corrected file name: ResumeIndexing.ps1
  docs/project/search/administration.md
Labels: Change sent to author, assessing_(C&L), devops-collab/tech, devops/prod, do-not-merge

#6462 Fixed typo
  docs/extend/get-started/node.md
Labels: Change sent to author, assessing_(C&L), devops-ecosystem/tech, devops/prod, do-not-merge

#6540 Small typo error in the YAML
  release-notes/2019/_shared/pipelines/sprint-160-update.md
Labels: Change sent to author, assessing_(C&L), devops-release-notes/tech, devops/prod, do-not-merge

#6584 fixing doc bug for download task
  docs/pipelines/yaml-schema.md
Labels: Change sent to author, assessing_(C&L), devops-cicd/tech, devops/prod, do-not-merge

#5438 Removing non-factual statements and bad guidance
  docs/repos/tfvc/decide-between-using-local-server-workspace.md
Labels: Change sent to author, assessing_(C&L), devops-code-tfvc/tech, devops/prod, do-not-merge

#6674 Fix typo in the word environment
  docs/pipelines/process/variables.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#6686 Fix typo
  docs/report/powerbi/data-connector-functions.md
Labels: Change sent to author, devops-analytics/tech, devops/prod, do-not-merge

#5053 Replace TFS with Azure DevOps Server
  docs/repos/git/manage-large-files.md
Labels: Change sent to author, assessing_(C&L), devops-code-git/tech, devops/prod, do-not-merge

#6720 Wiki: add/edit wiki fix link & table code layout
  docs/project/wiki/add-edit-wiki.md
Labels: Change sent to author, assessing_(C&L), devops-collab/tech, devops/prod, ready-to-merge

#6725 Add $ for string interpolation in C# code snippet
  docs/integrate/get-started/rest/samples.md
Labels: Change sent to author, devops-ecosystem/tech, devops/prod, ready-to-merge

#6679 Update tasks.md
  docs/pipelines/process/tasks.md
Labels: Change sent to author, assessing_(C&L), devops-cicd/tech, devops/prod, ready-to-merge

#6745 Update dotnet-core-tool-installer.md
  docs/pipelines/tasks/tool/dotnet-core-tool-installer.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#6771 Fix typo
  docs/java/standalone-tools.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#6788 Fixed spelling mistake
  docs/pipelines/process/variables.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge
