Repository MicrosoftDocs/azure-devops-docs, pull requests merged in 2019-06, with the labels that each got.

#4322 Fix typo
  docs/pipelines/process/phases.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#4276 typo: Double word "of"
  docs/demo-gen/use-demo-generator-v2.md
Labels: Change sent to author, devops-new-user/tech, devops/prod, do-not-merge

#4330 Incorret link to az devops extension
  release-notes/2019/_shared/general/sprint-152-update.md
Labels: Change sent to author, do-not-merge

#4354 Update task-groups.md
  docs/pipelines/library/task-groups.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#4455 typo: Double word "be"
  docs/pipelines/agents/hosted.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#4458 Typo
  docs/boards/backlogs/define-features-epics.md
Labels: Change sent to author, devops-agile/tech, devops/prod, do-not-merge

#4454 Suggestion for easier reading.
  docs/boards/backlogs/backlogs-boards-plans.md
Labels: Change sent to author, devops-agile/tech, devops/prod, do-not-merge

#4383 Update define-features-epics.md
  docs/boards/backlogs/define-features-epics.md
Labels: Change sent to author, devops-agile/tech, devops/prod, do-not-merge

#4452 Fix broken / incorrect links.
  docs/index.md
Labels: Change sent to author, devops-new-user/tech, devops/prod, do-not-merge

#4584 Update project-vision-status.md
  docs/organizations/projects/project-vision-status.md
Labels: Change sent to author, devops-collab/tech, devops/prod, do-not-merge

#4614 Add restoring to basic auth statement
  docs/pipelines/tasks/package/nuget.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#4553 comments to yaml snippet given
  docs/pipelines/build/triggers.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#4602 Resolve syncing conflicts from repo_sync_working_branch to master
  docs/organizations/accounts/create-organization.md
  docs/organizations/billing/buy-basic-access-add-users.md
  docs/organizations/billing/buy-basic-plus-test-plans.md
  docs/organizations/billing/buy-load-testing-vs.md
  docs/organizations/billing/buy-more-build-vs.md
  docs/organizations/billing/set-up-billing-for-your-organization-vs.md
  docs/organizations/billing/try-additional-features-vs.md
  docs/organizations/projects/connect-to-projects.md
  docs/organizations/projects/project-vision-status.md
  docs/organizations/public/code-search-public.md
  docs/organizations/public/create-public-project.md
  docs/organizations/public/invite-users-public.md
  docs/organizations/public/make-project-public.md
  docs/organizations/public/migration-checklist.md
  docs/organizations/public/service-limits-public.md
  docs/organizations/public/view-build-release-public.md
  docs/organizations/public/view-filter-work-items-public.md
  docs/organizations/public/view-project-dashboard-public.md
  docs/organizations/public/view-wiki-public.md
  docs/organizations/public/work-item-search-public.md
  docs/organizations/security/add-ad-aad-built-in-security-groups.md
  docs/organizations/settings/azure-devops-auditing.md
  docs/organizations/settings/naming-restrictions.md
  docs/project/wiki/add-edit-wiki.md
  docs/project/wiki/publish-repo-to-wiki.md
  docs/project/wiki/wiki-create-repo.md
  docs/user-guide/add-run-manual-tests.md
  docs/user-guide/code-with-git.md
  docs/user-guide/plan-track-work.md
  docs/user-guide/sign-up-invite-teammates.md
Labels: Change sent to author, devops-new-user/tech, devops/prod, do-not-merge

#4386 Fix group full name slashes
  docs/organizations/security/permissions.md
Labels: Change sent to author, devops-security/tech, devops/prod, do-not-merge
