Repository MicrosoftDocs/azure-devops-docs, pull requests merged in 2019-01, with the labels that each got.

#2970 Update hosted.md
  docs/pipelines/agents/hosted.md
Labels: Change sent to author, devops/prod, do-not-merge

#2960 Fixed spelling mistake on Azure DevOps organisation permissions
  docs/organizations/security/permissions.md
Labels: Change sent to author, devops/prod, do-not-merge

#2993 Removing yaml snippet
  docs/pipelines/tasks/utility/manual-intervention.md
Labels: Change sent to author, devops/prod, do-not-merge

#2990 Added Q&A for frequent GitHub issues
  docs/pipelines/tasks/utility/http-rest-api.md
Labels: Change sent to author, devops/prod, do-not-merge

#2992 Added Q&A based on question seen in Github Issues
  docs/pipelines/tasks/utility/publish-to-azure-service-bus.md
Labels: Change sent to author, devops/prod, do-not-merge

#3060 "Machine tags" renamed to "Required tags" to align with the UI
  docs/pipelines/apps/cd/howto-webdeploy-iis-deploygroups.md
Labels: Change sent to author, devops/prod, do-not-merge

#3027 chore: Remove duplicate Marketplace link
  docs/pipelines/targets/vmware.md
Labels: Change sent to author, devops/prod, do-not-merge

#3062 Update docs for Hosted macOS with guide how to change Xcode version for Xamarin
  docs/pipelines/agents/hosted.md
Labels: Change sent to author, devops/prod, do-not-merge

#3096 #478 Added steps to copy web.config files to root
  docs/pipelines/tasks/transforms-variable-substitution.md
Labels: Change sent to author, devops/prod, do-not-merge

#3079 Fix for bug #2542
  docs/pipelines/tasks/utility/publish-build-artifacts.md
Labels: Change sent to author, devops/prod, do-not-merge

#3056 Update publish.md for nuget publishing
  docs/artifacts/_shared/nuget/publish.md
Labels: Change sent to author, do-not-merge

#3013 Update administration.md
  docs/project/search/administration.md
Labels: Change sent to author, devops/prod, do-not-merge

#3092 Update service-containers.md
  docs/pipelines/process/service-containers.md
Labels: do-not-merge

#3152 Updated Wiki documentation for Ctrl+P keyboard shortcut
  docs/_shared/keyboard-shortcuts/wiki-shortcuts.md
Labels: Change sent to author, do-not-merge

#3102 Add new menu path for delivery plan
  docs/_shared/keyboard-shortcuts/delivery-plan-shortcuts.md
Labels: Change sent to author, do-not-merge
