Repository MicrosoftDocs/azure-devops-docs, pull requests merged in 2019-09, with the labels that each got.

#4523 limits.md: replace GVFS w/ VFS for Git
  docs/repos/git/limits.md
Labels: Change sent to author, devops-code-git/tech, devops/prod, do-not-merge

#4489 updating the purchasing terms for the Microsoft-Hosted jobs
  docs/pipelines/licensing/concurrent-jobs.md
Labels: Change sent to author, devops/prod, do-not-merge

#4440 Update old link & add related topic from UWP docs.
  docs/pipelines/apps/windows/universal.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#4214 Clarified how variables from variable groups should be used in YAML f…
  docs/pipelines/library/variable-groups.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#4126 Rename ASP.NET Core to ASP.NET
  docs/pipelines/apps/aspnet/build-aspnet-4.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#4097 Remove A: from Q&A section
  docs/pipelines/agents/hosted.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#4074 Changed description of project and pipeline fields
  docs/pipelines/tasks/_shared/yaml/DownloadPipelineArtifactV1.md
Labels: Change sent to author, do-not-merge

#4061 Un-comment AzureKeyVault@1 secretsFilter argument
  docs/pipelines/tasks/_shared/yaml/AzureKeyVaultV1.md
Labels: Change sent to author, do-not-merge

#3982 Use native PowerShell throughout example
  docs/pipelines/apps/_shared/prepare-aspnetcore-windows-vm.md
Labels: Change sent to author, do-not-merge

#3616 Fixed collapsed design on `what-is-azure-pipelines.md`.
  docs/pipelines/get-started/what-is-azure-pipelines.md
Labels: Change sent to author, devops/prod, do-not-merge

#3482 Changed images in to reflect new UI
  docs/pipelines/scripts/_img/control-panel-team-project-version-control-tab.png
  docs/pipelines/scripts/_img/control-panel-top-to-team-project.png
  docs/pipelines/scripts/_img/manage-project.png
Labels: Change sent to author, do-not-merge

#3996 fix reference to release retention dialog
  docs/pipelines/policies/retention.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#3958 Clarifies the solution argument of xamarin iOS
  docs/pipelines/tasks/build/xamarin-ios.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge
