Repository MicrosoftDocs/azure-devops-docs, pull requests merged in 2019-11, with the labels that each got.

#6202 Info about git.exe issue on Azure AD link/unlink
  docs/organizations/accounts/faq-azure-access.md
Labels: Change sent to author, assessing_(C&L), devops-accounts/tech, devops/prod, ready-to-merge

#5038 updated PAT Token by including username
  docs/integrate/get-started/rest/samples.md
Labels: Change sent to author, devops-ecosystem/tech, devops/prod, ready-to-merge

#6273 Changing wording to AKS cluster
  docs/pipelines/apps/cd/deploy-aks.md
Labels: Change sent to author, assessing_(C&L), devops-cicd/tech, devops/prod, do-not-merge

#5822 mutliple "Additional Invoke-Sqlcmd Arguments"
  docs/pipelines/tasks/deploy/sql-azure-dacpac-deployment.md
Labels: Change sent to author, assessing_(C&L), devops-cicd/tech, devops/prod, do-not-merge

#6287 Typo
  docs/organizations/security/restrict-access.md
Labels: Change sent to author, devops-security/tech, devops/prod, do-not-merge

#6247 fix typo in pipelines policies retention
  docs/pipelines/policies/retention.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#6028 Update set-secrets.md
  docs/pipelines/process/_shared/set-secrets.md
Labels: Change sent to author, assessing_(C&L), conceptual/tech, devops/prod, do-not-merge

#6302 Update download-pipeline-artifact.md
  docs/pipelines/tasks/utility/download-pipeline-artifact.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#6303 Update publish-pipeline-artifact.md
  docs/pipelines/tasks/utility/publish-pipeline-artifact.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#6304 Update PublishPipelineArtifactV1.md
  docs/pipelines/tasks/_shared/yaml/PublishPipelineArtifactV1.md
Labels: do-not-merge, review-team-triage

#6301 Update DownloadPipelineArtifactV2.md
  docs/pipelines/tasks/_shared/yaml/DownloadPipelineArtifactV2.md
Labels: do-not-merge, review-team-triage

#4592 Copy edit Task Group creation
  docs/pipelines/library/task-groups.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#6016 Show multi-job output variables for deployments
  docs/pipelines/process/variables.md
Labels: Change sent to author, assessing_(C&L), devops-cicd/tech, devops/prod, ready-to-merge

#6309 pipelines resource feature doc update
  docs/pipelines/yaml-schema.md
Labels: Change sent to author, assessing_(C&L), devops-cicd/tech, devops/prod, ready-to-merge

#6147 Modify the examples to add restore keys
  docs/pipelines/caching/index.md
Labels: Change sent to author, assessing_(C&L), devops-cicd/tech, devops/prod, do-not-merge

#6347 Update yaml-schema.md - fixing format issues with download task
  docs/pipelines/yaml-schema.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, ready-to-merge

#6345 Fix typos in deployment-jobs.md (pre-deploy --> preDeploy)
  docs/pipelines/process/deployment-jobs.md
Labels: Change sent to author, assessing_(C&L), devops-cicd/tech, devops/prod, do-not-merge

#6395 Typo "**@CurrentIteration**"→"**\@CurrentIteration**"
  docs/report/dashboards/configure-sprint-burndown.md
Labels: Change sent to author, devops-analytics/tech, devops/prod, do-not-merge

#6398 Fix typo
  docs/boards/boards/wip-limits.md
Labels: Change sent to author, devops-agile/tech, devops/prod, do-not-merge

#4494 Link was redirecting to create a publisher
  docs/extend/_shared/procedures/publish.md
Labels: Change sent to author, do-not-merge

#6314 Default iteration details
  docs/organizations/settings/set-iteration-paths-sprints.md
Labels: assessing_(C&L), ready-to-merge, review-team-triage

#4443 Remove link to dead extension.
  docs/project/feedback/index.md
Labels: Change sent to author, assessing_(C&L), devops-collab/tech, devops/prod, do-not-merge

#6313 Limitation on state-based rules
  docs/organizations/settings/work/custom-rules.md
Labels: Change sent to author, assessing_(C&L), devops-agile/tech, devops/prod, do-not-merge

#6310 Added NOTE about enabling SQL Server Auth mode
  docs/migrate/migration-import.md
Labels: Change sent to author, assessing_(C&L), devops-migrate/tech, devops/prod, do-not-merge

#6312 Corrections for work item operations permissioning
  docs/organizations/security/about-permissions.md
Labels: Change sent to author, assessing_(C&L), devops-security/tech, devops/prod, do-not-merge

#6411 Added links to API service health references
  docs/user-guide/service-status-info.md
Labels: Change sent to author, assessing_(C&L), devops-new-user/tech, devops/prod, ready-to-merge

#6399 Added a check for AZP_WORK
  docs/pipelines/agents/docker.md
Labels: Change sent to author, assessing_(C&L), devops-cicd/tech, devops/prod, ready-to-merge

#6391 fixing markdown in secure-files.md
  docs/pipelines/library/secure-files.md
Labels: Change sent to author, assessing_(C&L), devops-cicd/tech, devops/prod, do-not-merge

#6414 Clarify that variable groups can be used for passing secrets into YAML pipelines
  docs/pipelines/library/variable-groups.md
Labels: Change sent to author, assessing_(C&L), devops-cicd/tech, devops/prod, do-not-merge

#6431 Fixing two typos in the Deployment Jobs docs
  docs/pipelines/process/deployment-jobs.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, ready-to-merge

#6382 S160 deployment - changes to New Test Plans page
  docs/test/new-test-plans-page.md
Labels: Change sent to author, assessing_(C&L), devops-test/tech, devops/prod, do-not-merge

#6442 Update migrate.md to include a new analytics IP
  docs/migrate/migration-import.md
Labels: assessing_(C&L), do-not-merge, review-team-triage

#4457 Add a link to Views page
  docs/artifacts/how-to/delete-and-recover-packages.md
Labels: Change sent to author, assessing_(C&L), devops-artifacts/tech, devops/prod, do-not-merge

#6444 Add a warning for 2019.0.1 support
  docs/migrate/migration-overview.md
Labels: Change sent to author, assessing_(C&L), devops-migrate/tech, devops/prod, do-not-merge, review-team-triage

#6449 Update download-pipeline-artifact.md
  docs/pipelines/tasks/utility/download-pipeline-artifact.md
Labels: Change sent to author, assessing_(C&L), devops-cicd/tech, devops/prod, do-not-merge

#6494 Fix typo in Resolution link
  docs/boards/work-items/guidance/work-item-field.md
Labels: Change sent to author, devops-agile/tech, devops/prod, do-not-merge

#6497 fix typo in reference to manual intervention task
  docs/pipelines/tasks/deploy/kubernetes-manifest.md
Labels: Change sent to author, assessing_(C&L), devops-cicd/tech, devops/prod, do-not-merge
