Repository MicrosoftDocs/azure-devops-docs, pull requests merged in 2019-03, with the labels that each got.

#3535 Disable closing of issues marked as stale by stale bot
  .github/stale.yml
Labels: Change sent to author, do-not-merge

#2377 NuGet works with packages.config (not package.json!)
  docs/pipelines/languages/dotnet-core.md
Labels: Change sent to author, devops/prod

#3541 typo: Double word "must"
  docs/boards/backlogs/create-your-backlog.md
Labels: Change sent to author, devops/prod, do-not-merge

#3542 typo: Double word "the"
  docs/boards/queries/query-by-date-or-current-iteration.md
Labels: Change sent to author, devops/prod, do-not-merge

#3543 fix: docs/organizations/security/access-levels.md
  docs/organizations/security/access-levels.md
Labels: Change sent to author, devops/prod, do-not-merge

#3545 fix: release-notes/2013/jan-09-team-services.md
  release-notes/2013/jan-09-team-services.md
Labels: Change sent to author, devops/prod, do-not-merge

#3546 fix: docs/pipelines/artifacts/symbols.md
  docs/pipelines/artifacts/symbols.md
Labels: do-not-merge

#3603 Fix markdown for Eclipse/Team Explorer Everywhere link
  docs/user-guide/tools.md
Labels: Change sent to author, devops/prod, do-not-merge

#3582 Remove confusion with configuration shortcut
  docs/pipelines/tasks/_shared/yaml/DotNetCoreCLIV2.md
Labels: Change sent to author, do-not-merge

#3593 Grammar fix
  docs/pipelines/get-started-yaml.md
Labels: Change sent to author, devops/prod, do-not-merge

#3592 AngularJS is v1. Angular is the correct term for v2+
  docs/pipelines/languages/javascript.md
Labels: Change sent to author, devops/prod, do-not-merge

#3576 Project names can contain spaces.
  docs/_shared/sign-up-msft-account.md
Labels: Change sent to author, do-not-merge

#3554 fix: http://aka.ms/ -> https://aka.ms/
  docs/_shared/qa-why-cant-sign-in-msa-azuread-account.md
  docs/_shared/qa-why-no-owned-organizations.md
  docs/boards/get-started/manage-boards.md
  docs/extend/develop/add-build-task.md
  docs/extend/develop/add-dashboard-widget.md
  docs/extend/extension-report.md
  docs/extend/publish/_shared/create-publisher.md
  docs/extend/publish/overview.md
  docs/extend/publish/publicize.md
  docs/integrate/concepts/wit-client-om-deprecation.md
  docs/marketplace/extension-report.md
  docs/marketplace/get-tfs-extensions.md
  docs/marketplace/install-extension.md
  docs/marketplace/overview.md
  docs/marketplace/start-trial-extension.md
  docs/organizations/billing/_shared/qa-marketplace-support.md
  docs/organizations/billing/billing-faq.md
  docs/pipelines/archive/apps/aspnet/aspnet-4-ci-cd-vs-automatic.md
  docs/pipelines/archive/apps/aspnet/aspnetcore-docker-to-azure.md
  docs/pipelines/archive/apps/mobile/cordova-build.md
  docs/pipelines/archive/apps/mobile/cordova-command.md
  docs/pipelines/targets/vmware.md
  docs/repos/tfvc/branching-strategies-with-tfvc.md
  docs/user-guide/troubleshoot-connection.md
  release-notes/2014/aug-18-team-services.md
  release-notes/2014/may-12-team-services.md
  release-notes/2015/jun-03-team-services.md
  release-notes/2015/nov-18-team-services.md
  release-notes/2016/apr-13-team-services.md
  release-notes/2016/aug-17-team-services.md
  release-notes/2016/jan-25-team-services.md
  release-notes/2017/apr-19-team-services.md
  release-notes/2018/sprint-141-update.md
Labels: Change sent to author, devops/prod, do-not-merge

#3644 Removing redundant section about required permissions
  docs/repos/tfvc/add-check-policies.md
Labels: Change sent to author, devops/prod, do-not-merge

#3655 How to search filters on a Multi Repo Multi branch enviroment
  docs/project/search/code-search.md
Labels: Change sent to author, devops/prod, do-not-merge

#3698 Describe how to use .artifactignore files
  docs/pipelines/artifacts/pipeline-artifacts.md
Labels: Change sent to author, devops/prod, do-not-merge

#3641 added percentage
  docs/pipelines/_shared/set-variables-in-scripts.md
Labels: Change sent to author, do-not-merge

#3635 Clarify that pwsh will run PowerShell Core
  docs/pipelines/yaml-schema.md
Labels: do-not-merge

#3710 Update administration.md
  docs/project/search/administration.md
Labels: Change sent to author, devops/prod, do-not-merge

#3682 Have to change Microsoft.VSTS.Common.StackRank
  docs/reference/xml/reportable-fields-reference.md
Labels: Change sent to author, devops/prod, do-not-merge

#3617 Correct link to Subscriptions API
  docs/integrate/concepts/service-hooks.md
Labels: Change sent to author, devops/prod, do-not-merge

#3717 typo: Kingsom -> Kingdom
  docs/organizations/security/data-location.md
Labels: Change sent to author, devops/prod, do-not-merge

#3551 fix: MD003/heading-style/header-style
  docs/boards/backlogs/office/schedule-projects-using-microsoft-project.md
  docs/boards/backlogs/resolve-backlog-reorder-issues.md
  docs/boards/backlogs/work-item-template.md
  docs/boards/boards/filter-kanban-board.md
  docs/boards/boards/index.md
  docs/boards/queries/query-index-quick-ref.md
  docs/boards/queries/query-operators-variables.md
  docs/boards/queries/wiql-syntax.md
  docs/boards/work-items/about-work-items.md
  docs/boards/work-items/agile-glossary.md
  docs/boards/work-items/email-work-items.md
  docs/boards/work-items/follow-work-items.md
  docs/boards/work-items/guidance/agile-process-workflow.md
  docs/boards/work-items/guidance/changes-to-process-templates.md
  docs/boards/work-items/guidance/choose-process.md
  docs/boards/work-items/guidance/cmmi-process-workflow.md
  docs/boards/work-items/guidance/cmmi-process.md
  docs/boards/work-items/guidance/guidance-code-review-feedback-field-reference.md
  docs/boards/work-items/guidance/manage-process-templates.md
  docs/boards/work-items/guidance/scrum-process-workflow.md
  docs/boards/work-items/guidance/scrum-process.md
  docs/boards/work-items/guidance/work-item-field.md
  docs/boards/work-items/work-item-fields.md
  docs/integrate/previous-apis/chat/rooms.md
  docs/pipelines/get-started-designer.md
  docs/pipelines/tasks/utility/manual-intervention.md
  docs/project/wiki/migrate-extension-wiki-pages.md
  docs/reference/witadmin/manage-global-lists-for-work-item-types.md
  docs/reference/xml/categories-xml-element-reference.md
  docs/report/dashboards/widget-catalog.md
  docs/repos/git/merging.md
  docs/repos/git/use-ssh-keys-to-authenticate.md
  docs/repos/tfvc/add-check-policies.md
  docs/repos/tfvc/branches-command.md
  docs/repos/tfvc/day-life-alm-developer-suspend-work-fix-bug-conduct-code-review.md
  docs/repos/tfvc/unshelve-command.md
Labels: Change sent to author, devops/prod, do-not-merge

#3544 chore: Add passing MarkdownLint config
  .markdownlint.json
Labels: Change sent to author, do-not-merge

#3547 fix: MD039/no-space-in-links
  docs/boards/backlogs/create-your-backlog.md
  docs/boards/backlogs/define-features-epics.md
  docs/boards/backlogs/office/bulk-add-modify-work-items-excel.md
  docs/boards/backlogs/office/create-your-backlog-tasks-using-project.md
  docs/boards/backlogs/product-backlog-controls.md
  docs/boards/boards/customize-cards.md
  docs/boards/boards/definition-of-done.md
  docs/boards/get-started/customize-boards-agile.md
  docs/boards/get-started/customize-boards.md
  docs/boards/get-started/sign-up-invite-teammates-agile.md
  docs/boards/get-started/why-use-azure-boards.md
  docs/boards/plans/scaled-agile-framework.md
  docs/boards/queries/example-queries.md
  docs/boards/queries/query-numeric.md
  docs/boards/queries/titles-ids-descriptions.md
  docs/boards/queries/using-queries.md
  docs/boards/work-items/about-work-items.md
  docs/integrate/previous-apis/work/overview.md
  docs/migrate/migration-overview.md
  docs/migrate/phase-features-with-feature-flags.md
  docs/organizations/security/add-ad-aad-built-in-security-groups.md
  docs/organizations/security/add-users-team-project.md
  docs/organizations/security/change-individual-permissions.md
  docs/organizations/security/lookup-organization-owner-admin.md
  docs/organizations/security/set-git-tfvc-repository-permissions.md
  docs/organizations/security/set-project-collection-level-permissions.md
  docs/organizations/security/view-permissions.md
  docs/organizations/settings/about-teams-and-settings.md
  docs/organizations/settings/work/customize-process.md
  docs/pipelines/apps/index.md
  docs/pipelines/archive/apps/nodejs/nodejs-to-azure.md
  docs/pipelines/archive/news/rm-archived.md
  docs/pipelines/archive/release/previous-version/manage-your-release.md
  docs/pipelines/artifacts/build-artifacts.md
  docs/pipelines/targets/vmware.md
  docs/pipelines/tasks/deploy/service-fabric-compose-deploy.md
  docs/reference/add-modify-wit.md
  docs/reference/process-templates/add-wit-definitions-process-template.md
  docs/reference/process-templates/control-access-to-functional-areas.md
  docs/reference/tfs-ps-sync/xml-elements-added-to-wit-definition.md
  docs/reference/witadmin/manage-work-item-fields.md
  docs/reference/xml/linkscontroloptions-elements.md
  docs/reference/xml/linkscontroloptions-xml-elements.md
  docs/report/_shared/dashboard-prerequisites-tfs-2017-18.md
  docs/report/dashboards/widget-catalog.md
  docs/report/sql-reports/index.md
  docs/test/mtm/connect-microsoft-test-manager-to-your-team-project-and-test-plan.md
  docs/test/mtm/record-play-back-manual-tests.md
  docs/test/mtm/run-manual-tests-with-microsoft-test-manager.md
  docs/test/mtm/test-configurations-specifying-test-platforms.md
Labels: Change sent to author, devops/prod, do-not-merge

#3718 typo: Databse -> Database
  docs/pipelines/apps/cd/sql-server-actions.md
  docs/pipelines/targets/azure-sqldb.md
Labels: Change sent to author, devops/prod, do-not-merge

#3723 typo: elipses -> ellipses
  docs/pipelines/release/index.md
Labels: Change sent to author, devops/prod, do-not-merge

#3727 typo: extensibilty -> extensibility
  docs/pipelines/release/artifacts.md
Labels: Change sent to author, devops/prod, do-not-merge

#3729 typo: adherance -> adherence
  docs/test/reference-qa.md
Labels: Change sent to author, devops/prod, do-not-merge

#3736 typo: Double word "the"
  docs/migrate/migration-troubleshooting.md
Labels: Change sent to author, devops/prod, do-not-merge

#3761 Simple approach not supported in AzureDevOpsServer
  docs/pipelines/library/connect-to-azure.md
Labels: Change sent to author, devops/prod, do-not-merge
