Repository MicrosoftDocs/azure-devops-docs, pull requests merged in 2019-04, with the labels that each got.

#3832 Fix very minor typo
  docs/repos/git/create-a-readme.md
Labels: Change sent to author, devops-code-git/tech, devops/prod, do-not-merge

#3728 typo: announcment -> announcement
  docs/service-hooks/overview.md
Labels: Change sent to author, devops/prod, do-not-merge

#2863 Correct 'twine upload' command in Python package publishing docs
  docs/pipelines/artifacts/pypi.md
Labels: do-not-merge

#3894 Removed an erroneous command segment.
  docs/artifacts/quickstarts/universal-packages.md
Labels: Change sent to author, devops-artifacts/tech, devops/prod, do-not-merge

#3726 typo: alliows -> allows
  docs/boards/work-items/work-item-fields.md
Labels: Change sent to author, devops/prod, do-not-merge

#3724 typo: compability -> compatibility
  docs/reference/tfs-ps-sync/system-and-setup-requirements.md
Labels: Change sent to author, devops/prod, do-not-merge

#3719 typo: adition -> addition
  docs/boards/get-started/plan-track-work.md
  docs/boards/get-started/track-issues-tasks.md
Labels: Change sent to author, devops/prod, do-not-merge

#3715 typo: buttoms -> buttons
  docs/boards/queries/triage-work-items.md
Labels: Change sent to author, devops/prod, do-not-merge

#3908 Complete CLI steps using Azure DevOps extension
  docs/repos/git/share-your-code-in-git-cmdline.md
Labels: Change sent to author, devops-code-git/tech, devops/prod, do-not-merge

#3833 Update index.md
  docs/java/labs/settingvstsproject/index.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#3764 Update tfvc-repo.md
  docs/_shared/glossary-terms/tfvc-repo.md
Labels: Change sent to author, do-not-merge

#3738 fix: MD042/no-empty-links
  .markdownlint.json
  docs/pipelines/apps/cd/sql-server-actions.md
  release-notes/2018/jan-24-vsts.md
Labels: Change sent to author, devops/prod, do-not-merge

#3734 fix: Enable MD011
  .markdownlint.json
Labels: Change sent to author, do-not-merge

#3733 Update the git-svn utility link
  docs/repos/git/perform-migration-from-svn-to-git.md
Labels: Change sent to author, devops/prod, do-not-merge

#3731 fix: MD039/no-space-in-links
  .markdownlint.json
  docs/migrate/index.md
  docs/migrate/migrate-from-tfs.md
  docs/migrate/migration-import.md
  docs/migrate/migration-overview.md
  docs/migrate/migration-post-import.md
  docs/migrate/migration-processtemplates.md
  docs/migrate/migration-troubleshooting.md
  docs/project/navigation/set-favorites.md
Labels: Change sent to author, devops/prod, do-not-merge

#3730 fix: MD003/heading-style/header-style
  .markdownlint.json
  docs/pipelines/artifacts/nuget.md
Labels: do-not-merge

#3725 typo: valiation -> validation
  docs/pipelines/build/triggers.md
Labels: Change sent to author, devops/prod, do-not-merge

#3716 typo: phantomjd -> phantomjs
  docs/java/labs/dockerbuildagent/index.md
Labels: Change sent to author, devops/prod, do-not-merge

#3664 Update clean documentation to be accurate
  docs/pipelines/repos/pipeline-options-for-git.md
Labels: Change sent to author, devops/prod, do-not-merge

#3573 Update rebase.md
  docs/repos/git/rebase.md
Labels: Change sent to author, devops/prod, do-not-merge

#3550 fix: MD037/no-space-in-emphasis
  .markdownlint.json
  docs/reference/api-ref/partialopen.md
  docs/repos/tfvc/day-life-alm-developer-write-new-code-user-story.md
  release-notes/2014/jan-22-team-services.md
Labels: Change sent to author, devops/prod, do-not-merge

#3478 Clarify that Agent.WorkFolder may not be writable
  docs/pipelines/build/_shared/variables-server2019.md
  docs/pipelines/build/_shared/variables-vsts.md
Labels: Change sent to author, do-not-merge

#3720 fix: docs/integrate/concepts/dotnet-client-libraries.md
  docs/integrate/concepts/dotnet-client-libraries.md
Labels: Change sent to author, devops-ecosystem/tech, devops/prod, do-not-merge

#3949 Add probot move config file
  .github/move.yml
Labels: do-not-merge

#3914 fix: MD037/no-space-in-emphasis
  docs/boards/boards/add-columns.md
  docs/repos/tfvc/properties-or-info-command.md
  docs/user-guide/provide-feedback.md
Labels: Change sent to author, devops-new-user/tech, devops/prod, do-not-merge

#3721 typo: Migartion -> Migration
  docs/migrate/migration-processtemplates.md
Labels: Change sent to author, devops/prod, do-not-merge

#3934 typo: pipeines -> pipelines
  docs/pipelines/languages/docker.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#3967 Remove duplicated text
  docs/boards/backlogs/backlogs-boards-plans.md
Labels: Change sent to author, devops-agile/tech, devops/prod, do-not-merge

#3941 Removed Duplicate links for Feature and epics in azure boards
  docs/boards/work-items/about-work-items.md
Labels: Change sent to author, devops-agile/tech, devops/prod, do-not-merge

#3983 markdown/images/resizing: Remove note about resizing only working in certain contexts
  docs/project/wiki/markdown-guidance.md
Labels: Change sent to author, devops-collab/tech, devops/prod, do-not-merge

#3952 Clarify the relations between rerun threshold settings
  docs/pipelines/tasks/test/vstest.md
Labels: do-not-merge

#3915 fix: MD039/no-space-in-links
  docs/report/dashboards/widget-catalog.md
Labels: Change sent to author, devops-analytics/tech, devops/prod, do-not-merge

#3913 fix: MD003/heading-style/header-style
  docs/boards/queries/query-by-date-or-current-iteration.md
  docs/boards/queries/wiql-syntax.md
Labels: Change sent to author, devops-agile/tech, devops/prod, do-not-merge

#3735 fix: MD035/hr-style
  .markdownlint.json
  docs/repos/git/gitworkflow.md
  docs/repos/git/howto.md
  docs/test/load-test/reference-qa.md
Labels: Change sent to author, devops/prod, do-not-merge

#3549 fix: MD038/no-space-in-code
  .markdownlint.json
  docs/boards/boards/customize-cards.md
  docs/boards/boards/filter-kanban-board.md
  docs/boards/queries/search-box-queries.md
  docs/boards/queries/wiql-syntax.md
  docs/organizations/settings/work/import-process/customize-process.md
  docs/organizations/settings/work/import-process/resolve-errors.md
  docs/pipelines/agents/v2-osx.md
  docs/pipelines/tasks/deploy/azure-file-copy.md
  docs/reference/process-templates/define-groups-teams-permissions-plug-in.md
  docs/reference/process-templates/define-work-item-query-process-template.md
  docs/reference/tfs-ps-sync/remove-tfs-ps-integration.md
  docs/reference/xml/apply-rule-work-item-field.md
  docs/reference/xml/upload-or-download-the-microsoft-project-mapping-file.md
  docs/report/admin/manually-process-data-warehouse-and-cube.md
  docs/report/admin/rebuild-data-warehouse-and-cube.md
  docs/report/extend-analytics/odata-supported-features.md
  docs/report/extend-analytics/wit-analytics.md
  docs/repos/git/os-compatibility.md
  docs/repos/git/use-ssh-keys-to-authenticate.md
Labels: Change sent to author, devops-code-git/tech, devops/prod, do-not-merge

#4030 Update connect-organization-to-azure-ad.md
  docs/organizations/accounts/connect-organization-to-azure-ad.md
Labels: Change sent to author, devops-accounts/tech, devops/prod, do-not-merge

#4026 Update set-your-preferences.md
  docs/organizations/settings/set-your-preferences.md
Labels: Change sent to author, devops-collab/tech, devops/prod, do-not-merge

#3972 correcting grammar in team badge section
  release-notes/2019/sprint-150-update.md
Labels: Change sent to author, devops-release-notes/tech, devops/prod, do-not-merge

#4059 Update add-build-task.md
  docs/extend/develop/add-build-task.md
Labels: Change sent to author, devops-ecosystem/tech, devops/prod, do-not-merge

#4045 Typo correction
  docs/boards/work-items/guidance/choose-process.md
Labels: Change sent to author, devops-agile/tech, devops/prod, do-not-merge

#4070 Resolve syncing conflicts from repo_sync_working_branch to master
  docs/boards/_shared/version-vsts-tfs-2017-on.md
  docs/boards/backlogs/work-item-template.md
  docs/boards/work-items/_img/template/add-tags.png
  docs/boards/work-items/_img/template/area-path.png
  docs/boards/work-items/_img/template/custom-field.png
  docs/boards/work-items/_img/template/repo-steps-rendered.png
  docs/boards/work-items/_img/template/repo-steps.png
  docs/boards/work-items/quick-ref.md
  docs/boards/work-items/toc.yml
  docs/boards/work-items/work-item-template-examples.md
  docs/organizations/projects/_img/connect-projects/project-summary-page-choose-app-horz.png
  docs/organizations/projects/_img/connect-projects/project-summary-page-choose-app-vert.png
  docs/organizations/projects/_img/sign-out.png
  docs/organizations/projects/connect-to-projects.md
  docs/organizations/security/add-users-team-project.md
  docs/organizations/settings/manage-teams.md
  docs/pipelines/_shared/azure-prerequisites.md
  docs/pipelines/_shared/ci-cd-prerequisites-vsts.md
  docs/pipelines/_shared/prerequisites.md
  docs/pipelines/apps/c-cpp/gcc.md
  docs/pipelines/apps/cd/azure/aspnet-core-to-acr.md
  docs/pipelines/apps/windows/dot-net.md
  docs/pipelines/apps/windows/universal.md
  docs/pipelines/create-first-pipeline.md
  docs/pipelines/get-started-multiplatform.md
  docs/pipelines/languages/_shared/_img/add-service-connection-dialog-box.png
  docs/pipelines/languages/_shared/clean-up-resources.md
  docs/pipelines/languages/_shared/create-pipeline-after-maven-template-selected.md
  docs/pipelines/languages/_shared/create-pipeline-after-template-selected.md
  docs/pipelines/languages/_shared/create-pipeline-alternative-outcomes.md
  docs/pipelines/languages/_shared/create-pipeline-before-template-selected.md
  docs/pipelines/languages/_shared/create-project.md
  docs/pipelines/languages/_shared/create-service-connection.md
  docs/pipelines/languages/_shared/deployment-variables.md
  docs/pipelines/languages/_shared/get-code-before-sample-repo.md
  docs/pipelines/languages/_shared/run-pipeline.md
  docs/pipelines/languages/_shared/sign-in-azure-cli.md
  docs/pipelines/languages/_shared/sign-in-azure-pipelines.md
  docs/pipelines/languages/java-function.md
  docs/pipelines/languages/java-webapp.md
  docs/pipelines/toc.yml
  docs/repos/git/merging.md
  docs/user-guide/add-run-manual-tests.md
  docs/user-guide/toc.yml
  release-notes/index.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#4037 Add information related to Git LFS in git import
  docs/repos/git/import-git-repository.md
Labels: Change sent to author, devops-code-git/tech, devops/prod, do-not-merge

#4095 Publish link was linking to Create Publisher
  docs/extend/develop/add-build-task.md
Labels: Change sent to author, devops-ecosystem/tech, devops/prod, do-not-merge

#4104 Disable stale bot completely at this time
  .github/stale.yml
Labels: Change sent to author, do-not-merge
