Repository MicrosoftDocs/azure-devops-docs, pull requests merged in 2020-04, with the labels that each got.

#7785 Removed VSTS Reference
  docs/pipelines/release/artifacts.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#7789 Fixed a broken link to "Analytics data model"
  docs/report/dashboards/analytics-extension.md
Labels: Change sent to author, devops-analytics/tech, devops/prod, do-not-merge

#7818 Update data-location.md
  docs/organizations/security/data-location.md
Labels: Change sent to author, devops-security/tech, devops/prod, ready-to-merge

#7827 Update data-location.md
  docs/organizations/security/data-location.md
Labels: Change sent to author, devops-security/tech, devops/prod, ready-to-merge

#7850 Update python-webapp.md
  docs/pipelines/ecosystems/python-webapp.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#7821 added githubenterprise to list of repository types
  docs/pipelines/process/resources.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd/tech, devops/prod, ready-to-merge

#7833 Added missing display name for restore
  docs/pipelines/ecosystems/dotnet-core.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd/tech, devops/prod, ready-to-merge

#7420 Update kubernetes.md
  docs/pipelines/tasks/deploy/kubernetes.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd/tech, devops/prod, do-not-merge

#7913 fixed grammar 🧐
  docs/organizations/security/data-location.md
Labels: Change sent to author, devops-security/tech, devops/prod, ready-to-merge

#7801 Fix issues with keyboard shortcuts doc:
  docs/project/navigation/keyboard-shortcuts.md
Labels: Change sent to author, aq-pr-triaged, devops-collab/tech, devops/prod, do-not-merge

#7820 Update data-protection.md
  docs/organizations/security/data-protection.md
Labels: Change sent to author, aq-pr-triaged, devops-security/tech, devops/prod, do-not-merge

#7736 escape example URLs
  docs/integrate/get-started/authentication/oauth.md
Labels: Change sent to author, aq-pr-triaged, devops-code-tfvc/tech, devops/prod, do-not-merge

#7895 Plugin name was changed
  docs/java/download-android-studio-plug-in.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd/tech, devops/prod, do-not-merge

#7925 Update expressions.md
  docs/pipelines/process/expressions.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, ready-to-merge

#7873 Explain global/job level variable mapping for secrets
  docs/pipelines/process/variables.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd/tech, devops/prod, ready-to-merge

#7940 Update Hosted Image versions
  docs/pipelines/ecosystems/xamarin.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd/tech, devops/prod, ready-to-merge

#7954 Fix Azure DevOps Service feed locator url
  docs/artifacts/how-to/set-up-upstream-sources.md
Labels: Change sent to author, aq-pr-triaged, devops-artifacts/tech, devops/prod, ready-to-merge

#7992 Grunt -> gulp
  docs/pipelines/tasks/build/gulp.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#7443 Updated "Delay task" YAML snippet
  docs/pipelines/tasks/includes/yaml/DelayV1.md
Labels: aq-pr-triaged, devops-cicd-process/tech, devops/prod, do-not-merge, review-team-triage

#8023 Fix typo
  docs/pipelines/tasks/build/visual-studio-build.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#7923 Updating ARG task doc with FAQ
  docs/pipelines/tasks/deploy/azure-resource-group-deployment.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd/tech, devops/prod, do-not-merge

#6774 #4108 Add demand that dotnet required to generate report
  docs/pipelines/tasks/test/publish-code-coverage-results.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd/tech, devops/prod, do-not-merge

#7388 Adding .net 4.6.2 or higher as the prereq for vstest & ptr task documentation
  docs/pipelines/tasks/test/publish-test-results.md
  docs/pipelines/tasks/test/vstest.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd/tech, devops/prod, do-not-merge

#7739 Added other open-source load testing alternatives
  docs/test/load-test/overview.md
Labels: Change sent to author, aq-pr-triaged, devops-test/tech, devops/prod, ready-to-merge

#8063 Fix rendering of images
  docs/marketplace/faq-extensions.md
Labels: Change sent to author, aq-pr-triaged, devops-marketplace/tech, devops/prod, ready-to-merge

#8085 Make a specification
  docs/pipelines/tasks/deploy/sql-azure-dacpac-deployment.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd/tech, devops/prod, do-not-merge

#8092 Typo "**@Mention**"→"**\@Mention**"
  docs/notifications/at-mentions.md
Labels: Change sent to author, devops-collab/tech, devops/prod, ready-to-merge

#8109 making inline code easier to identify
  docs/repos/git/repository-settings.md
Labels: Change sent to author, devops-code-git/tech, devops/prod, do-not-merge

#8103 DR update.
  docs/organizations/security/data-protection.md
Labels: Change sent to author, aq-pr-triaged, devops-security/tech, devops/prod, do-not-merge

#8128 Fix Minor typo for 'minor' run number. Resolves Issue #8074
  docs/pipelines/process/expressions.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#8142 Mention that Maven task overwrites MAVEN_OPTS
  docs/pipelines/release/caching.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#6615 Anaconda environments changes
  docs/pipelines/ecosystems/anaconda.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd/tech, devops/prod, do-not-merge

#7964 Adds "workspace" property to "deployment" schema
  docs/pipelines/yaml-schema.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd/tech, devops/prod, investigating, ready-to-merge

#8151 Correct menu entry
  docs/pipelines/toc.yml
Labels: aq-pr-triaged, do-not-merge, review-team-triage
