Repository MicrosoftDocs/azure-devops-docs, pull requests merged in 2020-05, with the labels that each got.

#8192 Update start-using-azure-artifacts.md
  docs/artifacts/start-using-azure-artifacts.md
Labels: Change sent to author, devops-artifacts/tech, devops/prod, ready-to-merge

#8232 Added a powershell example for the key in service endpoint cli
  docs/cli/service_endpoint.md
Labels: Change sent to author, aq-pr-triaged, devops-ref/tech, devops/prod, do-not-merge

#7976 Use build configuration variable
  docs/pipelines/ecosystems/dotnet-core.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd/tech, devops/prod, ready-to-merge

#8115 Corrected runOnce strategy example
  docs/pipelines/process/deployment-jobs.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd/tech, devops/prod, ready-to-merge

#8311 Fixes Issue 8297 - updates triggers.md
  docs/pipelines/build/triggers.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, ready-to-merge

#8321 Added missing brackets to close the OData filter
  docs/report/powerbi/sample-pipelines-allpipelines.md
Labels: Change sent to author, devops-analytics/tech, devops/prod, do-not-merge

#8015 Clarify pull request variables
  docs/pipelines/build/includes/variables-hosted.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd/tech, devops/prod, ready-to-merge

#8046 Add GitHub Enterprise &Bitbucket as a supported Code Repo
  docs/pipelines/process/resources.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd/tech, devops/prod, ready-to-merge

#8343 Missing punctuation
  docs/pipelines/ecosystems/containers/build-image.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#7819 Update linux dockeragent
  docs/pipelines/agents/docker.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd/tech, devops/prod, ready-to-merge

#8073 Fixed indentation of environment yaml example
  docs/pipelines/yaml-schema.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd/tech, devops/prod, ready-to-merge

#8105 Encourage use of System.PreferGitFromPath variable when using LFS on hosted windows agents
  docs/pipelines/repos/pipeline-options-for-git.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd-repos/tech, devops-cicd/tech, devops/prod, ready-to-merge

#8140 Change link for k6/load impact
  docs/test/load-test/overview.md
Labels: Change sent to author, aq-pr-triaged, devops-test/tech, devops/prod, ready-to-merge

#8157 Add two spaces in yaml snippet
  docs/pipelines/tasks/package/pip-authenticate.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd/tech, devops/prod, ready-to-merge

#7951 adding note on gatekeeper alerts
  docs/pipelines/agents/agents.md
  docs/pipelines/agents/v2-osx.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd-agents/tech, devops-cicd/tech, devops/prod, do-not-merge

#8383 Remove surplus paranthesis
  docs/boards/work-items/agile-glossary.md
Labels: Change sent to author, devops-agile/tech, devops/prod, do-not-merge

#7238 Update PublishBuildArtifactsV1.md
  docs/pipelines/tasks/includes/yaml/PublishBuildArtifactsV1.md
Labels: aq-pr-triaged, devops-cicd-process/tech, devops/prod, do-not-merge, review-team-triage

#8421 Add namespaces
  docs/cli/security_tokens.md
Labels: Change sent to author, devops-ref/tech, devops/prod, do-not-merge

#8377 Update container-phases.md
  docs/pipelines/process/container-phases.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd-process/tech, devops/prod, ready-to-merge

#8459 expressions.md: update code comment
  docs/pipelines/process/expressions.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd-process/tech, devops/prod, ready-to-merge

#8460 added deprecated/read-only namespaces
  docs/cli/security_tokens.md
Labels: Change sent to author, aq-pr-triaged, devops-ref/tech, devops/prod, do-not-merge
