Repository MicrosoftDocs/azure-devops-docs, pull requests merged in 2020-03, with the labels that each got.

#7451 Fix documentation for Descendants/any()
  docs/report/powerbi/sample-boards-featureprogress.md
Labels: Change sent to author, aq-pr-triaged, devops-analytics/tech, devops/prod, do-not-merge

#7495 Update pom-and-settings.md
  docs/artifacts/includes/maven/pom-and-settings.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd/tech, devops/prod, do-not-merge

#7527 Remove extra markdown characters
  docs/project/wiki/publish-repo-to-wiki.md
Labels: Change sent to author, devops-collab/tech, devops/prod, ready-to-merge

#7529 Update list of available AZ PowerShell module versions in Azure PowerShell v4 task
  docs/pipelines/tasks/deploy/azure-powershell.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#7531 Fix missing escape of | in table.
  docs/pipelines/tasks/utility/cache.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#7484 update java-function.md
  docs/pipelines/ecosystems/java-function.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd/tech, devops/prod, ready-to-merge

#7553 added details to manage deployments
  docs/pipelines/policies/permissions.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, ready-to-merge

#7554 Pipeline decorator: full stop at end of sentence
  docs/extend/develop/add-pipeline-decorator.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, ready-to-merge

#7555 Publish marketplace: full stop sentence
  docs/extend/publish/overview.md
Labels: Change sent to author, devops-ecosystem/tech, devops/prod, do-not-merge

#7552 Updated alternate credentials notice
  docs/includes/alt-creds-deprecation-notice.md
Labels: Change sent to author, aq-pr-triaged, devops/prod, ready-to-merge

#7557 Clarify nuget.exe usage
  docs/pipelines/tasks/package/nuget.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd/tech, devops/prod, ready-to-merge

#7579 Add advice on sharing VssConnection
  docs/integrate/get-started/client-libraries/samples.md
Labels: Change sent to author, devops-ecosystem/tech, devops/prod, ready-to-merge

#6689 Update universal-packages.md
  docs/pipelines/tasks/package/universal-packages.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd/tech, devops/prod, do-not-merge, review-team-triage

#7583 Typo correction in 2FA description
  docs/repos/git/set-up-credential-managers.md
Labels: Change sent to author, devops-code-git/tech, devops/prod, do-not-merge

#7602 Correct typo
  docs/repos/git/pull-requests.md
Labels: Change sent to author, devops-code-git/tech, devops/prod, do-not-merge

#7664 Removed extra s on TestResults EntitySet
  docs/report/extend-analytics/data-model-analytics-service.md
Labels: Change sent to author, aq-pr-triaged, devops-analytics/tech, devops/prod, do-not-merge

#7694 Update auth-schemes.md
  docs/extend/develop/auth-schemes.md
Labels: Change sent to author, devops-ecosystem/tech, devops/prod, ready-to-merge

#7688 Update variables.md
  docs/pipelines/build/variables.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd/tech, devops/prod, ready-to-merge

#6576 Download feature issue with version 0.14.0 and up
  docs/pipelines/artifacts/universal-packages.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd/tech, devops/prod, ready-to-merge

#7751 Updated the Why can't I find members from my co...
  docs/organizations/accounts/faq-user-and-permissions-management.md
Labels: Change sent to author, devops-accounts/tech, devops/prod, ready-to-merge

#7450 tweaks to caching examples
  docs/pipelines/release/caching.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd/tech, devops/prod, ready-to-merge
