Repository MicrosoftDocs/azure-devops-docs, pull requests merged in 2020-02, with the labels that each got.

#7167 Update delete-your-organization.md
  docs/organizations/accounts/delete-your-organization.md
Labels: Change sent to author, assessing_(C&L), devops-accounts/tech, devops/prod, ready-to-merge

#7197 Remove empty bullet point
  docs/repos/tfvc/overview.md
Labels: Change sent to author, devops-code-tfvc/tech, devops/prod, do-not-merge

#7204 fix verbe tense
  docs/pipelines/process/templates.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#7171 Update stages.md
  docs/pipelines/process/stages.md
Labels: Change sent to author, assessing_(C&L), devops-cicd/tech, devops/prod, ready-to-merge

#7227 basic grammar
  docs/pipelines/agents/v2-windows.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#6017 Update download-intellij-plug-in.md
  docs/java/download-intellij-plug-in.md
Labels: Change sent to author, assessing_(C&L), devops-cicd/tech, devops/prod, do-not-merge

#7187 Add Azure File Copy Example
  docs/pipelines/tasks/includes/yaml/AzureFileCopyV3.md
Labels: assessing_(C&L), do-not-merge, review-team-triage

#6226 Better definition for locking strategy
  docs/repos/git/lock-branches.md
Labels: Change sent to author, assessing_(C&L), devops-code-git/tech, devops/prod, do-not-merge

#6817 Fix git lfs fetch/push commands
  docs/repos/git/import-git-repository.md
Labels: Change sent to author, assessing_(C&L), devops-code-git/tech, devops/prod, do-not-merge

#6131 Add Retention Policy Detail
  docs/repos/git/restore-deleted-branch.md
Labels: Change sent to author, assessing_(C&L), devops-code-git/tech, devops/prod, do-not-merge

#7244 Update typo in bash.md (Azure Pipelines Task)
  docs/pipelines/tasks/utility/bash.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#7254 Update yaml-schema.md
  docs/pipelines/yaml-schema.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#7272 update environment variable casing in samples
  docs/pipelines/tasks/utility/bash.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, ready-to-merge

#7260 rm extra pipe character
  docs/pipelines/tasks/utility/bash.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, ready-to-merge

#7274 Re-fix reverted change from merge conflict
  docs/pipelines/tasks/utility/bash.md
Labels: Change sent to author, assessing_(C&L), devops-cicd/tech, devops/prod, do-not-merge

#7278 Update resolve-orphaned-organization.md
  docs/organizations/accounts/resolve-orphaned-organization.md
Labels: Change sent to author, devops-accounts/tech, devops/prod, ready-to-merge

#7282 Updating the mermaid url to point to the current updated one and addi…
  docs/project/wiki/wiki-markdown-guidance.md
Labels: Change sent to author, devops-collab/tech, devops/prod, ready-to-merge

#7292 Resolve syncing conflicts from repo_sync_working_branch to master
  docs/organizations/accounts/media/change-organization-ownership/not-member-of-organization-azure-active-directory-administrator.png
  docs/organizations/accounts/resolve-orphaned-organization.md
  docs/organizations/billing/buy-more-build-vs.md
  docs/organizations/security/permissions.md
  docs/organizations/toc.yml
  docs/pipelines/release/deploy-pull-request-builds.md
  docs/project/wiki/publish-repo-to-wiki.md
Labels: Change sent to author, assessing_(C&L), devops-collab/tech, devops/prod, do-not-merge

#7304 customize pipeline: case typo
  docs/pipelines/customize-pipeline.md
Labels: Change sent to author, devops-cicd/tech, devops/prod, do-not-merge

#7316 Fix typo
  docs/report/sql-reports/reporting-services-reports.md
Labels: Change sent to author, devops-analytics/tech, devops/prod, do-not-merge

#7326 AzureFileCopyV3 example YAML highlighting
  docs/pipelines/tasks/includes/yaml/AzureFileCopyV3.md
Labels: assessing_(C&L), do-not-merge, review-team-triage

#7331 Update resolve-orphaned-organization.md
  docs/organizations/accounts/resolve-orphaned-organization.md
Labels: Change sent to author, devops-accounts/tech, devops/prod, ready-to-merge

#7334 Added note on copy/paste
  docs/notifications/at-mentions.md
Labels: Change sent to author, devops-collab/tech, devops/prod, ready-to-merge

#6362 Update set-permissions.md
  docs/pipelines/policies/set-permissions.md
Labels: Change sent to author, assessing_(C&L), devops-cicd/tech, devops/prod, do-not-merge

#7357 Fix missing word in a link
  docs/boards/backlogs/work-item-template.md
Labels: Change sent to author, devops-agile/tech, devops/prod, do-not-merge

#7136 Remove extra WIQL code
  docs/boards/queries/wiql-syntax.md
Labels: Change sent to author, assessing_(C&L), devops-agile/tech, devops/prod, do-not-merge

#6075 Updated the labels for the access control set
  docs/pipelines/scripts/git-commands.md
Labels: Change sent to author, assessing_(C&L), devops-cicd/tech, devops/prod, do-not-merge

#7090 Remove outdated note at end of page
  docs/extend/develop/add-build-task.md
Labels: Change sent to author, assessing_(C&L), devops-ecosystem/tech, devops/prod, ready-to-merge

#7115 Fixed links to code samples
  docs/integrate/previous-apis/tfs/projects.md
Labels: Change sent to author, assessing_(C&L), devops-ecosystem/tech, devops/prod, ready-to-merge

#7132 Consolidate exceptions to regions
  docs/organizations/security/data-location.md
Labels: Change sent to author, assessing_(C&L), devops-security/tech, devops/prod, ready-to-merge

#5724 Creating consistency with semicolons
  docs/repos/git/create-pr-status-server.md
Labels: Change sent to author, assessing_(C&L), devops-code-git/tech, devops/prod, do-not-merge

#6680 Update artifacts-overview.md
  docs/pipelines/artifacts/artifacts-overview.md
Labels: Change sent to author, assessing_(C&L), devops-cicd/tech, devops/prod, ready-to-merge

#6471 Add PHP/Composer caching example
  docs/pipelines/release/caching.md
Labels: Change sent to author, assessing_(C&L), devops-cicd/tech, devops/prod, do-not-merge

#4655 Note about UNIX permissions on Build artifacts
  docs/pipelines/artifacts/build-artifacts.md
Labels: Change sent to author, assessing_(C&L), devops-cicd/tech, devops/prod, do-not-merge

#3959 Adds sample yaml to the app signing docs
  docs/pipelines/apps/mobile/app-signing.md
Labels: Change sent to author, assessing_(C&L), devops-cicd/tech, devops/prod, ready-to-merge, review-team-triage

#7407 Bug in Publish python distribution to Azure Artifacts feed
  docs/pipelines/tasks/package/twine-authenticate.md
Labels: Change sent to author, assessing_(C&L), devops-cicd/tech, devops/prod, do-not-merge

#6257 .exe removal in examples + anonymous note
  docs/artifacts/tutorials/private-powershell-library.md
Labels: Change sent to author, assessing_(C&L), devops-artifacts/tech, devops/prod, do-not-merge

#7092 Update test-glossary.md
  docs/pipelines/test/test-glossary.md
Labels: Change sent to author, aq-pr-triaged, devops-cicd/tech, devops/prod, do-not-merge
